export const FETCH_EVENT = 'ORM/FETCH_EVENT'
export const CREATE_EVENT = 'ORM/CREATE_EVENT'
export const UPDATE_EVENT = 'ORM/UPDATE_EVENT'
export const REMOVE_EVENT = 'ORM/REMOVE_EVENT'

export const FETCH_TRANSACTION = 'ORM/FETCH_TRANSACTION'
export const CREATE_TRANSACTION = 'ORM/CREATE_TRANSACTION'
export const UPDATE_TRANSACTION = 'ORM/UPDATE_TRANSACTION'
export const REMOVE_TRANSACTION = 'ORM/REMOVE_TRANSACTION'

export const FETCH_BLOCK = 'ORM/FETCH_BLOCK'
export const CREATE_BLOCK = 'ORM/CREATE_BLOCK'
export const UPDATE_BLOCK = 'ORM/UPDATE_BLOCK'
export const REMOVE_BLOCK = 'ORM/REMOVE_BLOCK'

export const CREATE_EVENT_CT_INDEX = 'ORM/CREATE_EVENT_CT_INDEX'
export const UPDATE_EVENT_CT_INDEX = 'ORM/UPDATE_EVENT_CT_INDEX'
export const REMOVE_EVENT_CT_INDEX = 'ORM/REMOVE_EVENT_CT_INDEX'

export const CREATE_CONTRACT = 'ORM/CREATE_CONTRACT'
export const UPDATE_CONTRACT = 'ORM/UPDATE_CONTRACT'
export const REMOVE_CONTRACT = 'ORM/REMOVE_CONTRACT'