export const FETCH_EVENT = 'FETCH_EVENT'
export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const REMOVE_EVENT = 'REMOVE_EVENT'

export const FETCH_TRANSACTION = 'FETCH_TRANSACTION'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION'

export const FETCH_BLOCK = 'FETCH_BLOCK'
export const CREATE_BLOCK = 'CREATE_BLOCK'
export const UPDATE_BLOCK = 'UPDATE_BLOCK'
export const REMOVE_BLOCK = 'REMOVE_BLOCK'

export const CREATE_EVENT_CT_INDEX = 'CREATE_EVENT_CT_INDEX'
export const UPDATE_EVENT_CT_INDEX = 'UPDATE_EVENT_CT_INDEX'
export const REMOVE_EVENT_CT_INDEX = 'REMOVE_EVENT_CT_INDEX'